name: 'Publish new release'

on:
  push:
    tags: ['v*']

# This workflow will trigger on each push of a tag that starts with a "v" to create or update a GitHub release, build your app, and upload the artifacts to the release.
# Useful links:
# https://github.com/marketplace/actions/build-and-upload-rust-binary-to-github-releases
# https://github.com/marketplace/actions/rust-release-binary
# https://github.com/cargo-bins/cargo-binstall/blob/main/.github/workflows/release-packages.yml
# https://github.com/trunk-rs/trunk/blob/main/.github/workflows/release.yaml
# https://goreleaser.com/quick-start/

env:
  binary_name: firefox-session-ui-egui

jobs:
  build:
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: macos-latest # for Arm based macs (M1 and above).
            target: aarch64-apple-darwin
  
          - platform: macos-latest # for Intel based macs.
            target: x86_64-apple-darwin

          - platform: ubuntu-latest
            target: aarch64-unknown-linux-gnu
  
          - platform: ubuntu-latest
            target: armv7-unknown-linux-gnueabihf
  
          - platform: ubuntu-latest
            target: x86_64-unknown-linux-gnu
  
          - platform: windows-latest
            target: x86_64-pc-windows-msvc
            ext: .exe

    steps:
      - name: Building ${{ matrix.target }}
        run: echo "${{ matrix.target }}"
  
      - uses: actions/checkout@master
      - uses: actions-rs/toolchain@v1.0.1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
  
      # For linux, it's necessary to use cross from the git repository to avoid glibc problems
      # Ref: https://github.com/cross-rs/cross/issues/1510
      - uses: actions-rs/cargo@v1
        with:
          use-cross: contains(matrix.target, 'linux')
          command: build
          args: --verbose --release --target=${{ matrix.target }}

      - name: Post Build | Move binary
        run: |
          mkdir uploads
          mv target/${{ matrix.target }}/release/${{ env.binary_name }}${{ matrix.ext }} uploads/${{ env.binary_name }}${{ matrix.ext }}

      - name: Post Build | Prepare artifacts [zip]
        if: matrix.platform == 'windows-latest'
        working-directory: uploads
        run: |
          7z a ${{ env.binary_name }}-${{ matrix.target }}.zip ${{ env.binary_name }}${{ matrix.ext }}

      - name: Post Build | Prepare artifacts [tar.gz]
        if: matrix.platform != 'windows-latest'
        working-directory: uploads
        run: |
          tar --create --gzip --verbose --file  ${{ env.binary_name }}-${{ matrix.target }}.tar.gz ${{ env.binary_name }}${{ matrix.ext }}

      - name: Post Build | Remove binary (now inside compressed artifact)
        working-directory: uploads
        run: |
          rm ${{ env.binary_name }}${{ matrix.ext }}

      - name: Post Build | Display structure of uploads folder
        run: ls uploads

      - name: Post Build | Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.binary_name }}-${{ matrix.target }}
          path: uploads/*
          retention-days: 1
          if-no-files-found: error

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Download binaries from previous job
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - name: Display structure of downloaded files
        run: ls artifacts

      # Upload release asset:  https://github.com/actions/upload-release-asset
      # which recommends:      https://github.com/softprops/action-gh-release
      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: artifacts/*
